Controllers/ArtController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;
using Microsoft.EntityFrameworkCore;
using System.IO;
using GalleryStation.Models;

namespace GalleryStation.Controllers;

public class ArtController : Controller
{

    private GSContext _context;
    private readonly IWebHostEnvironment _webHost;

    public ArtController(IWebHostEnvironment webHost, GSContext context)
    {
        _webHost = webHost;
        _context = context;
    }

    private int? uid
    {
        get
        {
            return HttpContext.Session.GetInt32("UUID");
        }
    }

    private bool loggedIn
    {
        get
        {
            return uid != null;
        }
    }

    [HttpGet("/art/new")]
    public IActionResult NewArtwork()
    {
        if (!loggedIn)
        {
            return RedirectToAction("Index", "User");
        }
        return View("AddArtwork");
    }

    [HttpPost("/art/create")]
    public IActionResult Create(Art newArt)
    {

        if (!loggedIn || uid == null)
        {
            return RedirectToAction("Index");
        }

        if (ModelState.IsValid == false)
        {
            return NewArtwork();
        }

        newArt.UserId = (int)uid;
        _context.Arts.Add(newArt);
        _context.SaveChanges();
        return RedirectToAction("Index", "User");
    }

    [HttpPost("art/save")]
    public async Task<IActionResult> Save(Art newart, IFormFile imgfile)
    {
        var saveimg = Path.Combine(_webHost.WebRootPath, "img", imgfile.FileName);
        string imgext = Path.GetExtension(imgfile.FileName);
        if (imgext == ".jpg" || imgext == ".png")
        {
            using (var uploading = new FileStream(saveimg, FileMode.Create))
            {
                await imgfile.CopyToAsync(uploading);
                ViewData["Message"] = imgfile;
                newart.ArtPiece = imgfile.FileName;
                newart.UserId = (int)uid;
                _context.Arts.Add(newart);
                _context.SaveChanges();
                return RedirectToAction("Index", "User");
            }
        }
        else
        {
            ViewData["Message"] = "Only Images that are allowed are .jpn and .png";
        }
        return RedirectToAction("Index", "User");
    }

    [HttpGet("/art/{artId}")]
    public IActionResult OneArt(int artId)
    {
        if (!loggedIn || uid == null)
        {
            return RedirectToAction("Login", "User");
        }
        Art? oneArt = _context.Arts
            .Include(art => art.Creator)
            .FirstOrDefault(art => art.ArtId == artId);

        if (oneArt == null)
        {
            return RedirectToAction("Index");
        }

        return View("ArtInfo", oneArt);
    }

    [HttpPost("/art/{deletedArtId}/delete")]
    public IActionResult Delete(int deletedArtId)
    {
        if(!loggedIn)
        {
            return RedirectToAction("Login");
        }

        Art? artToBeDeleted = _context.Arts.FirstOrDefault(art => art.ArtId == deletedArtId);
        if(artToBeDeleted != null)
        {
            _context.Arts.Remove(artToBeDeleted);
            _context.SaveChanges();
        }
        return RedirectToAction("Index", "User");
    }




    [HttpGet("/shopping/cart")]
    public IActionResult Cart()
    {
        if (!loggedIn)
        {
            return RedirectToAction("Index", "User");
        }

        List<ShoppingCart> cartList = _context.CartItems.Include( a=> a.PurchasedArt).Where( a=> a.UserId == HttpContext.Session.GetInt32("UUID")).ToList();

        ViewBag.Cart = cartList;

        return View("Cart");
    }

    [HttpPost("art/{artToBeBought}/buy")]
    public IActionResult AddToCart(int artToBeBought)
    {
        if(!loggedIn)
        {
            return RedirectToAction("Index", "User");
        }
        ShoppingCart newItem = new ShoppingCart()
        {
            UserId = (int)uid,
            ArtId = artToBeBought
        };
        
        // newItem.UserId = (int)uid;
        // newItem.ArtId = artToBeBought;
        _context.CartItems.Add(newItem);
        _context.SaveChanges();
        return RedirectToAction("Cart", newItem);
    }


}

Views/Shared/Cart.cshtml
@model ShoppingCart
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LoginRegistration.styles.css" asp-append-version="true" />
    <title>GalleryStation</title>
</head>

<body>
    <div class="mx-auto border-light border-bottom border-3 shadow-lg">
        <div class="d-flex justify-content-between align-items-center bg-dark text-light p-2">

            <h1 class="h2 text-bold"><img class="log" src="./img/icons8-artstation-64.png">GalleryStation</h1>

            <div class="d-flex align-items-center">

                <a href="/shopping/cart"><img src="../img/cart_icon.png" alt="wuh" class="car"></a>
                <img src="./img/icons8-bot-64.png" alt="nya"
                    class='rob rounded-circle profile-pic border border-dark border-4'>
                <div>
                    <h6>Profile</h6>
                </div>
                <!-- <a class="nav-link active btn btn-rounded bg-gradient bg-info text-white m-1" href="#">Market</a> -->
                <form>
                    <button class='btn block-cube block-cube-hover' formaction="/">
                        <div class='bg-top'>
                            <div class='bg-inner'></div>
                        </div>
                        <div class='bg-right'>
                            <div class='bg-inner'></div>
                        </div>
                        <div class='bg'>
                            <div class='bg-inner'></div>
                        </div>
                        <div class='text text-white'>
                            Market
                        </div>
                    </button>
                </form>
                <!-- <a class="nav-link active btn btn-rounded bg-gradient bg-info text-white m-1" href="#">Profile</a> -->
                <form>
                    <button class='btn block-cube block-cube-hover' formaction="/">
                        <div class='bg-top'>
                            <div class='bg-inner'></div>
                        </div>
                        <div class='bg-right'>
                            <div class='bg-inner'></div>
                        </div>
                        <div class='bg'>
                            <div class='bg-inner'></div>
                        </div>
                        <div class='text text-white'>
                            Profile
                        </div>
                    </button>
                </form>
                <!-- <a class="nav-link active btn btn-rounded bg-gradient bg-info text-white m-1" href="/art/new">Add
                    Art</a> -->
                <form>
                    <button class='btn block-cube block-cube-hover' formaction="/art/new">
                        <div class='bg-top'>
                            <div class='bg-inner'></div>
                        </div>
                        <div class='bg-right'>
                            <div class='bg-inner'></div>
                        </div>
                        <div class='bg'>
                            <div class='bg-inner'></div>
                        </div>
                        <div class='text text-white'>
                            Add Art
                        </div>
                    </button>
                </form>
                <form asp-controller="User" asp-action="Logout" method="POST">
                    <button class="nav-link active btn btn-rounded bg-info bg-gradient text-white m-1">Logout</button>
                </form>
                <!-- <form asp-controller="User" asp-action="Logout" method="POST">
                    <button class='btn block-cube block-cube-hover' formaction="/register">
                        <div class='bg-top'>
                            <div class='bg-inner'></div>
                        </div>
                        <div class='bg-right'>
                            <div class='bg-inner'></div>
                        </div>
                        <div class='bg'>
                            <div class='bg-inner'></div>
                        </div>
                        <div class='text text-white'>
                            Logout
                        </div>
                    </button>
                </form> -->
                <!-- <a class="nav-link active btn btn-rounded bg-gradient bg-info text-white m-1"
                    href="/register">Register</a> -->
                <form>
                    <button class='btn block-cube block-cube-hover' formaction="/register">
                        <div class='bg-top'>
                            <div class='bg-inner'></div>
                        </div>
                        <div class='bg-right'>
                            <div class='bg-inner'></div>
                        </div>
                        <div class='bg'>
                            <div class='bg-inner'></div>
                        </div>
                        <div class='text text-light'>
                            Register
                        </div>
                    </button>
                </form>
                <!-- <a class="nav-link active btn btn-rounded bg-gradient bg-info text-white m-1" href="/login">Login</a> -->
                <form>
                    <button class='btn block-cube block-cube-hover' formaction="/login">
                        <div class='bg-top'>
                            <div class='bg-inner'></div>
                        </div>
                        <div class='bg-right'>
                            <div class='bg-inner'></div>
                        </div>
                        <div class='bg'>
                            <div class='bg-inner'></div>
                        </div>
                        <div class='text text-light'>
                            Log In
                        </div>
                    </button>
                </form>
            </div>
        </div>
    </div>
    <div>
        <div>
            <h1>Checkout Cart </h1>
            <img src="./img/cart_icon.png" alt="wuh">
        </div>
        <div>
            <table class="table table-striped table-dark table-bordered">
                <tr>
                    <th>imgThumbnail</th>
                    <th>Title</th>
                    <th>Quantity</th>
                    <th>Price</th>
                </tr>
                    @if(ViewBag.Cart != null)
                    {
                        @foreach (ShoppingCart cart in ViewBag.Cart)
                        {
                            <tr>
                                <td>
                                    <img class="thumbnail" src="~/img/@cart.PurchasedArt.ArtPiece" alt="random">
                                </td>
                                <td>@cart.PurchasedArt.Title</td>
                                <td>1</td>
                                <td>@cart.PurchasedArt.Price.ToString("C")</td>
                            </tr>
                        }
                    }
            </table>
        </div>
        <div>
            <form>
                <label>Name</label>
                <input type="text">
                <label>Address</label>
                <input type="text">
                <label>Credit Card Number</label>
                <input type="text">
                <label>Expiration Date</label>
                <input type="text">
                <label>CVC Number</label>
                <input type="text">
            </form>
        </div>
    </div>



</body>

</html>

Views/Shared/Index.cshtml
@model List<Art>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LoginRegistration.styles.css" asp-append-version="true" />
    <title>GalleryStation</title>
</head>

<body>
    <div class="mx-auto border-light border-bottom border-3 shadow-lg">
        <div class="d-flex justify-content-between align-items-center bg-dark text-light p-2">

            <h1 class="h2 text-bold"><img class="log" src="./img/icons8-artstation-64.png">GalleryStation</h1>

            <div class="d-flex align-items-center">

                <a href="/shopping/cart"><img src="../img/cart_icon.png" alt="wuh" class="car"></a>
                <img src="./img/icons8-bot-64.png" alt="nya"
                    class='rob rounded-circle profile-pic border border-dark border-4'>
                <div>
                    <h6>Profile</h6>
                </div>
                <!-- <a class="nav-link active btn btn-rounded bg-gradient bg-info text-white m-1" href="#">Market</a> -->
                <form>
                    <button class='btn block-cube block-cube-hover' formaction="/">
                        <div class='bg-top'>
                            <div class='bg-inner'></div>
                        </div>
                        <div class='bg-right'>
                            <div class='bg-inner'></div>
                        </div>
                        <div class='bg'>
                            <div class='bg-inner'></div>
                        </div>
                        <div class='text text-white'>
                            Market
                        </div>
                    </button>
                </form>
                <!-- <a class="nav-link active btn btn-rounded bg-gradient bg-info text-white m-1" href="#">Profile</a> -->
                <form>
                    <button class='btn block-cube block-cube-hover' formaction="/">
                        <div class='bg-top'>
                            <div class='bg-inner'></div>
                        </div>
                        <div class='bg-right'>
                            <div class='bg-inner'></div>
                        </div>
                        <div class='bg'>
                            <div class='bg-inner'></div>
                        </div>
                        <div class='text text-white'>
                            Profile
                        </div>
                    </button>
                </form>
                <!-- <a class="nav-link active btn btn-rounded bg-gradient bg-info text-white m-1" href="/art/new">Add
                    Art</a> -->
                <form>
                    <button class='btn block-cube block-cube-hover' formaction="/art/new">
                        <div class='bg-top'>
                            <div class='bg-inner'></div>
                        </div>
                        <div class='bg-right'>
                            <div class='bg-inner'></div>
                        </div>
                        <div class='bg'>
                            <div class='bg-inner'></div>
                        </div>
                        <div class='text text-white'>
                            Add Art
                        </div>
                    </button>
                </form>
                <form asp-controller="User" asp-action="Logout" method="POST">
                    <button class="nav-link active btn btn-rounded bg-info bg-gradient text-white m-1">Logout</button>
                </form>
                <!-- <form asp-controller="User" asp-action="Logout" method="POST">
                    <button class='btn block-cube block-cube-hover' formaction="/register">
                        <div class='bg-top'>
                            <div class='bg-inner'></div>
                        </div>
                        <div class='bg-right'>
                            <div class='bg-inner'></div>
                        </div>
                        <div class='bg'>
                            <div class='bg-inner'></div>
                        </div>
                        <div class='text text-white'>
                            Logout
                        </div>
                    </button>
                </form> -->
                <!-- <a class="nav-link active btn btn-rounded bg-gradient bg-info text-white m-1"
                    href="/register">Register</a> -->
                <form>
                    <button class='btn block-cube block-cube-hover' formaction="/register">
                        <div class='bg-top'>
                            <div class='bg-inner'></div>
                        </div>
                        <div class='bg-right'>
                            <div class='bg-inner'></div>
                        </div>
                        <div class='bg'>
                            <div class='bg-inner'></div>
                        </div>
                        <div class='text text-light'>
                            Register
                        </div>
                    </button>
                </form>
                <!-- <a class="nav-link active btn btn-rounded bg-gradient bg-info text-white m-1" href="/login">Login</a> -->
                <form>
                    <button class='btn block-cube block-cube-hover' formaction="/login">
                        <div class='bg-top'>
                            <div class='bg-inner'></div>
                        </div>
                        <div class='bg-right'>
                            <div class='bg-inner'></div>
                        </div>
                        <div class='bg'>
                            <div class='bg-inner'></div>
                        </div>
                        <div class='text text-light'>
                            Log In
                        </div>
                    </button>
                </form>
            </div>
        </div>
    </div>
    <div class="displayArt border border-3 border-light bg-dark text-light rounded p-3 m-5">
        <div class="text-end">
            <div>Forest , Cyber, Fantasy</div>
        </div>
        <div>
            @if (ViewBag.Art != null)
            {
                @foreach (Art a in ViewBag.Art)
                {
                    bool alreadyInCart = a.ListOfOrders.Any(c => c.ArtId == a.ArtId);
                    <div class="imgAlign">
                        <div class="imgDis">
                            <img class="thumbnail" src="../img/@a.ArtPiece">
                        </div>

                        <div class="text-center">
                            <div style="display: flex; align-items: center; justify-content: space-evenly;">
                                <h2><a href="/art/@a.ArtId">@a.Title</a></h2>
                                <h3>@a.Price.ToString("C")</h3>
                            </div>
                            <div style="display: flex; align-items: center; justify-content: space-evenly;">
                                @if (a.UserId == Context.Session.GetInt32("UUID") && alreadyInCart == false)
                                {
                                    <form asp-controller="Art" asp-route-artToBeBought="@a.ArtId" asp-action="AddToCart" method="POST">
                                        <button class="btn btn-success">Add to Cart!</button>
                                    </form>
                                }
                                else
                                {
                                    <a href="/shopping/cart">
                                        <button class="btn btn-success">View in Cart</button>
                                    </a>
                                    <h1>
                                        user : @a.UserId
                                    </h1>
                                    <h4>

                                    curr_user : @Context.Session.GetInt32("UUID")
                                    </h4>
                                    <h4>

                                    art : @a.ArtId
                                    </h4>
                                }
                            </div>
                            <form asp-controller="Art" asp-action="Delete" asp-route-deletedArtId="@a.ArtId" method="POST"
                        style="margin-top: 5px;">
                                <button class="btn btn-danger"> Delete </button>
                            </form>

                        </div>
                    </div>
                }
            }
        </div>
    </div>
</body>



</html>

Views/Shared/Profile.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LoginRegistration.styles.css" asp-append-version="true" />
    <title>GalleryStation</title>
</head>
<body>    
    <div class="mx-auto border-light border-bottom border-3 shadow-lg">
        <div class="d-flex justify-content-between align-items-center bg-dark text-light p-2">

            <h1 class="h2 text-bold"><img class="log" src="./img/icons8-artstation-64.png">GalleryStation</h1>

            <div class="d-flex align-items-center">

                <a href="/shopping/cart"><img src="../img/cart_icon.png" alt="wuh" class="car"></a>
                <img src="./img/icons8-bot-64.png" alt="nya"
                    class='rob rounded-circle profile-pic border border-dark border-4'>
                <div>
                    <h6>Profile</h6>
                </div>
                <!-- <a class="nav-link active btn btn-rounded bg-gradient bg-info text-white m-1" href="#">Market</a> -->
                <form>
                    <button class='btn block-cube block-cube-hover' formaction="/">
                        <div class='bg-top'>
                            <div class='bg-inner'></div>
                        </div>
                        <div class='bg-right'>
                            <div class='bg-inner'></div>
                        </div>
                        <div class='bg'>
                            <div class='bg-inner'></div>
                        </div>
                        <div class='text text-white'>
                            Market
                        </div>
                    </button>
                </form>
                <!-- <a class="nav-link active btn btn-rounded bg-gradient bg-info text-white m-1" href="#">Profile</a> -->
                <form>
                    <button class='btn block-cube block-cube-hover' formaction="/">
                        <div class='bg-top'>
                            <div class='bg-inner'></div>
                        </div>
                        <div class='bg-right'>
                            <div class='bg-inner'></div>
                        </div>
                        <div class='bg'>
                            <div class='bg-inner'></div>
                        </div>
                        <div class='text text-white'>
                            Profile
                        </div>
                    </button>
                </form>
                <!-- <a class="nav-link active btn btn-rounded bg-gradient bg-info text-white m-1" href="/art/new">Add
                    Art</a> -->
                <form>
                    <button class='btn block-cube block-cube-hover' formaction="/art/new">
                        <div class='bg-top'>
                            <div class='bg-inner'></div>
                        </div>
                        <div class='bg-right'>
                            <div class='bg-inner'></div>
                        </div>
                        <div class='bg'>
                            <div class='bg-inner'></div>
                        </div>
                        <div class='text text-white'>
                            Add Art
                        </div>
                    </button>
                </form>
                <form asp-controller="User" asp-action="Logout" method="POST">
                    <button class="nav-link active btn btn-rounded bg-info bg-gradient text-white m-1">Logout</button>
                </form>
                <!-- <form asp-controller="User" asp-action="Logout" method="POST">
                    <button class='btn block-cube block-cube-hover' formaction="/register">
                        <div class='bg-top'>
                            <div class='bg-inner'></div>
                        </div>
                        <div class='bg-right'>
                            <div class='bg-inner'></div>
                        </div>
                        <div class='bg'>
                            <div class='bg-inner'></div>
                        </div>
                        <div class='text text-white'>
                            Logout
                        </div>
                    </button>
                </form> -->
                <!-- <a class="nav-link active btn btn-rounded bg-gradient bg-info text-white m-1"
                    href="/register">Register</a> -->
                <form>
                    <button class='btn block-cube block-cube-hover' formaction="/register">
                        <div class='bg-top'>
                            <div class='bg-inner'></div>
                        </div>
                        <div class='bg-right'>
                            <div class='bg-inner'></div>
                        </div>
                        <div class='bg'>
                            <div class='bg-inner'></div>
                        </div>
                        <div class='text text-light'>
                            Register
                        </div>
                    </button>
                </form>
                <!-- <a class="nav-link active btn btn-rounded bg-gradient bg-info text-white m-1" href="/login">Login</a> -->
                <form>
                    <button class='btn block-cube block-cube-hover' formaction="/login">
                        <div class='bg-top'>
                            <div class='bg-inner'></div>
                        </div>
                        <div class='bg-right'>
                            <div class='bg-inner'></div>
                        </div>
                        <div class='bg'>
                            <div class='bg-inner'></div>
                        </div>
                        <div class='text text-light'>
                            Log In
                        </div>
                    </button>
                </form>
            </div>
        </div>
    </div>
</body>

</html>